title: Meet AdSDK  Tutorials
baseurl: "/nextgen-adsdk-android-release/additional-docs"
url: "https://vm-mobile-sdk.github.io/nextgen-adsdk-android-release/"
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
include:
  - favicon.ico
