title: Meet AdSDK Tutorials
baseurl: "/nextgen-adsdk-android-release/4.6.0"
url: "https://vm-mobile-sdk.github.io/nextgen-adsdk-android-release/4.6.0/"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
include:
  - favicon.ico
