name: Deploy Documentation
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get docs artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "docs.zip"
          token: ${{ secrets.GH_TOKEN }}
      - name: Switch to gh_pages branch
        run: |
          git config --global user.email "mail@example.com"
          git config --global user.name "documentation deployer"
          git fetch origin gh_pages:gh_pages
          git checkout gh_pages
          git pull --rebase origin gh_pages
      - name: Update docs folder
        run: |
          rm -r docs
          unzip docs.zip -d ./
          rm docs.zip
      - name: Commit and push changes to gh_pages
        run: |
          git add docs
          git commit -m "Update HTML documentation"
          git push -u origin gh_pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}