name: Update Documentation
on: 
  repository_dispatch:
    types: [doc-update-trigger]
permissions:
  contents: write
jobs:
  doc_update:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh_pages_test
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
        working-directory: ./docs
      - name: Load documentation
        run: |
          repo_owner="VM-Mobile-SDK"
          repo_name="nextgen-adsdk-android"
          artifact_id="${{ github.event.client_payload.artifact_id }}"
          api_url="https://api.github.com/repos/$repo_owner/$repo_name/actions/artifacts/$artifact_id/zip"
          doc_version="${{ github.event.client_payload.release_number }}"
          temp_dir=temp

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$api_url" -o "docs.zip" || exit 1

          mkdir -p "$temp_dir"
          unzip -o "docs.zip" -d "$temp_dir"
          cp -r "$temp_dir/$doc_version" "docs/"
          cp -r "$temp_dir/_$doc_version" "docs/tutorials/"

          rm "docs.zip" & rm "$temp_dir"
      - name: Cleanup old documentation metadata
        run: bundle exec jekyll clean
        working-directory: ./docs
      - name: Update documentation files
        run: bash update_doc_versions.sh 5
        working-directory: ./scripts
      - name: Build documentation
        run: bundle exec jekyll build
        working-directory: ./docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: mobilesdk
          author_email: mobilesdk@virtualminds.com
          message: 'Documentation updated'